name: eclass
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.1
  font_awesome_flutter: ^8.8.1
  percent_indicator: ^2.1.5
#  video_player: ^0.10.12+2
  pit_slider_carousel: ^0.1.0
  path_morph: ^1.0.1
  fading_edge_scrollview: ^1.1.0
  http: ^0.12.2
  razorpay_flutter: ^1.2.2
  fluttertoast: ^7.0.4
  page_transition: ^1.1.6
  flutter_secure_storage: ^3.3.5
  flutter_swiper: ^1.1.6
  cached_network_image: ^2.3.2+1
  image_picker: ^0.6.6+5
  file_picker: ^2.1.5
  flutter_paystack: ^1.0.4+1
  flutter_credit_card: ^0.1.3
  youtube_player_flutter: ^7.0.0+7
  shimmer: ^1.1.1
  dio: ^3.0.10
  flutter_widget_from_html: ^0.5.1+1
  stripe_api: ^1.1.0
  stripe_payment: ^1.0.8
  screen: ^0.0.5
  http_auth: ^0.3.0
  auto_size_text: ^2.1.0
  html_unescape: ^1.0.2
  sticky_headers: ^0.1.8+1
  paytm: ^1.0.8
  youtube_player_iframe: ^1.2.0+2
  flutter_inappwebview: ^4.0.0+4
  better_player: ^0.0.43
  webview_flutter: ^1.0.7
  flutter_facebook_login: ^3.0.0
  firebase_core: ^0.5.2+1
  firebase_auth: ^0.18.3+1
  google_sign_in: ^4.5.6

  flutter_zoom_plugin:
    git:
      url: git://github.com/decodedhealth/flutter_zoom_plugin.git
      ref: 0.0.8
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/placeholder/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Mada
      fonts:
        - asset: fonts/Mada-Regular.ttf
          weight: 400
        - asset: fonts/Mada-Bold.ttf
          weight: 700
        - asset: fonts/Mada-SemiBold.ttf
          weight: 600
        - asset: fonts/Mada-Medium.ttf
          weight: 500
        - asset: fonts/Mada-Light.ttf
          weight: 300
        - asset: fonts/Mada-Black.ttf
          weight: 800
    - family: icomoon
      fonts:
        - asset: assets/custom_icons/custom-icons.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
